### ISSUE TITLE
Filter features not available in recruitment focuses

### ISSUE THREAD

**Issue by doncoop** [bluestillidie00/tcs5#28]
Seems like a bar is missing from the recruitment focuses which means you cannot:

 - Change the view
 - Filter based on interest in transfer (short)
 - Filter based on interest in loan (short)
 - Filter (scouting filter button with full filter options)

Default and your skin attached

Default
<img width="1560" alt="Screenshot 2023-10-23 at 07 16 19" src="https://github.com/bluestillidie00/tcs5/assets/5167455/696b0346-be26-4974-b193-e6e751e8cb49">

TCS
<img width="1551" alt="Screenshot 2023-10-23 at 07 16 49" src="https://github.com/bluestillidie00/tcs5/assets/5167455/c80fd539-2fc1-4dc0-8e87-8d8d5b4aedda">

**Comment by bluestillidie00** [comment]
Might be a remnant from copying the skin over from last year. 

Will take a look, fhanks
