### ISSUE TITLE
Add information to transfer activity page

### ISSUE THREAD

**Issue by davidrpfarinha** [bluestillidie00/tcs5#30]
Hey there,

I would like to suggest a potential quality of life improvement over the transfer activity page (if doable) where we would add the origin and destination club.
Ideally, I wouldn't need to navigate to the In or Out tabs to confirm if it is a player I'm selling or purchasing.
![image](https://github.com/bluestillidie00/tcs5/assets/7164089/0ebcdb9f-0134-4a78-9ede-e4b57683521e)

I understand that is not a priority, and it is not a huge problem (you should know who you have acquired), but when you have the real-world type of save can be helpful.

To some extend, I even believe this should be added to the game itself where it could either say "joins" or "leaves".

Once again, thanks for the great work (and for adding the footedness to the player popup).

Cheers.

**Comment by davidrpfarinha** [comment]
> Can't guarantee i'll get round to it, but I will have a look!

Appreciated, as always!

**Comment by bluestillidie00** [comment]
Hardcoded unfortunately
