### ISSUE TITLE
Text is same colour as staff header

### ISSUE THREAD

**Issue by bluestillidie00** [bluestillidie00/tcs5#33]
![Screenshot2023-10-23at19_45_06 thumb png 458d925f5a327365cbbe7944843247e2](https://github.com/bluestillidie00/tcs5/assets/49170677/b75dee61-76ce-46ad-8af1-62e140e926ba)

**Comment by davidrpfarinha** [comment]
Tried to replicate this without success.
![image](https://github.com/bluestillidie00/tcs5/assets/7164089/994aa1c3-6a5a-4f66-aae8-20e652761831)

Are you still able, @bluestillidie00?

**Comment by bluestillidie00** [comment]
![image](https://github.com/bluestillidie00/tcs5/assets/49170677/918957d3-b42a-4845-9c78-a2a7ac4b6860)
Yeah been able to replicate. Will just remove the background and set the colour to a static colour
