### ISSUE TITLE
Player Overview - under attributes - condition & match sharpness not aligned

### ISSUE THREAD

**Issue by davidrpfarinha** [bluestillidie00/tcs5#35]
Hey there,

I have found that the those two elements aren't aligned.

![image](https://github.com/bluestillidie00/tcs5/assets/7164089/ecda2bfb-ebe2-44e9-b124-07bdf55fa5dc)

Couldn't find where the player attributes panel is defined to be able to change it.

**Comment by bluestillidie00** [comment]
yeah tried aligning it but had no luck myself. Should just be in player/player attributes panel
