### ISSUE TITLE
Background on some buttons have the same color as the text

### ISSUE THREAD

**Issue by joaopegas** [bluestillidie00/tcs5#37]
Hello again,

Just have this "little bug" happening sometimes, where the "Instant Result"/"Proceed" buttons seem to get the same color and we can't see what's in there.

Pre-game 

![image](https://github.com/bluestillidie00/tcs5/assets/18729106/1adf5a45-26e8-41be-9c4a-bb0ba04799fe)

Then if I mouse over:

![image](https://github.com/bluestillidie00/tcs5/assets/18729106/4b3bb10a-7578-48a6-af5c-76767163f0f0)

Another example, when already in-game trying to proceed to the "Match Preview":

![image](https://github.com/bluestillidie00/tcs5/assets/18729106/a9c3435b-4371-45ca-87d0-c0997839d83d)

Mouse over it:

![image](https://github.com/bluestillidie00/tcs5/assets/18729106/f2510865-700b-4549-adb8-b46eaf046469)

Once again, thanks for all the amazing work!

**Comment by bluestillidie00** [comment]
both were fixed with a commit earlier today

**Comment by joaopegas** [comment]
Great work!! Thanks!
