### ISSUE TITLE
Bug - Information is not visible when using 1920x1080

### ISSUE THREAD

**Issue by davidrpfarinha** [bluestillidie00/tcs5#52]
![image](https://github.com/bluestillidie00/tcs5/assets/7164089/75d295bf-1126-49a6-84c8-2b98850f2165)

Should we consider removing this information from the Ability panel?
![image](https://github.com/bluestillidie00/tcs5/assets/7164089/d2e55c5d-a023-4fb1-b43b-a74a9b5ad109)

**Comment by bluestillidie00** [comment]
Yeah it's definitely worth a shout
