### ISSUE TITLE
Add player name to profile panel

### ISSUE THREAD

**Issue by Pjstaab** [bluestillidie00/tcs5#54]
When looking at a player profile pop out thing it's hard to tell who you're actually looking at. Higher up in the list it pops out next to the person you're looking at but as soon as the box collides with the bottom of the screen you lose all context. 

Here I'm looking at James Prenderville since the box pops out under his name. 
![image](https://github.com/bluestillidie00/tcs5/assets/1230210/6aacf7e4-70a3-4b39-a3d9-0fe4e914a16c)

Here you might think I'm looking at Myles Walford but I'm actually looking at Ryan Miller who you can't see under the pop out. 
![image](https://github.com/bluestillidie00/tcs5/assets/1230210/9ce26d7f-853d-43e4-a194-3a552b1218cd)

**Comment by bluestillidie00** [comment]
Will investigate
