### ISSUE TITLE
Stats bar when progressing days, stat information not visible for clubs with light colors

### ISSUE THREAD

**Issue by joaopegas** [bluestillidie00/tcs5#55]
My club color is white, so, sometimes when I'm progressing the game I see the stats bar as in the picture where the detail is a yellow really difficult to see.

![image](https://github.com/bluestillidie00/tcs5/assets/18729106/5b3b7050-5e84-49d5-a4a5-b484fa1d9939)

**Comment by bluestillidie00** [comment]
Plan to remake the processing screen for a following update
