### ISSUE TITLE
Player page not appearing as it should

### ISSUE THREAD

**Issue by samshattock** [bluestillidie00/tcs5#58]
Hey, it seems that my skin is consistent with how it should look except for one issue - the player page seems to have defaulted to something more like the default FM skin, there are no tabs and the player face is in front of the club logo rather than the jersey. I'm using 1920 x 1080 with 100% zoom, and I have version 1.2 of the skin loaded. I have included other screenshots to demonstrate how the skin otherwise appears as it should. 

![Screenshot 2023-12-14 at 12 26 04 pm](https://github.com/bluestillidie00/tcs5/assets/52322599/e67b30a4-f16a-4b1e-9dd2-e03d41ec545e)

![Screenshot 2023-12-14 at 12 26 47 pm](https://github.com/bluestillidie00/tcs5/assets/52322599/676ee6af-038e-4585-acdf-c518dd8b7d28)
![Screenshot 2023-12-14 at 12 27 00 pm](https://github.com/bluestillidie00/tcs5/assets/52322599/c791dcc7-9941-46db-9e06-7cc1f67128c6)

![Screenshot 2023-12-14 at 12 24 49 pm](https://github.com/bluestillidie00/tcs5/assets/52322599/dd7b6533-6d62-4987-9abb-186f5832f438)
![Screenshot 2023-12-14 at 12 25 16 pm](https://github.com/bluestillidie00/tcs5/assets/52322599/edc66eaa-92d7-4b29-8137-1518f2e88226)

**Comment by bluestillidie00** [comment]
go im to preferences, search for landing page and change it from attributes to profile
