### ISSUE TITLE
Bug - Quick Selection On Tactics Screen Not Displaying Players Mid-Match

### ISSUE THREAD

**Issue by bnuybunbun** [bluestillidie00/tcs5#68]
When attempting to use the Quick Selection feature (the one activated by pressing the arrow on the player name), no players are displayed. 
This issue occurs exclusively mid-match. 
The problem persists across both the standard WTCS tactics screen and the smaller variant from the Mod Folder.
I have tried every filter combination to troubleshoot the issue without any success.

Resolution: 2560x1440
Scaling: 100%

![20240323185941_1](https://github.com/bluestillidie00/tcs5/assets/122939237/120d257e-472e-480c-9572-81a029a17786)

**Comment by bluestillidie00** [comment]
Will have a look!
