### ISSUE TITLE
Faces overlapping on news tab

### ISSUE THREAD

**Issue by oysterkeeper** [bluestillidie00/tcs5#74]
![fm_JEXC4kIe34](https://github.com/bluestillidie00/tcs5/assets/164952026/4c29647b-f914-4787-8529-ce4e5f6ca514)

Doesn't happen every time but pretty often.

**Comment by bluestillidie00** [comment]
Yeah unfortuntely its a weird resolution thing, to fix it the widths of everything would have to be set to static which would just lead  to other things looking weird.
