### ISSUE TITLE
Bug - Scout Report panel in the player preview appears empty since v1.3.0

### ISSUE THREAD

**Issue by Jokaes** [bluestillidie00/tcs5#78]
I'm using Full Screen (2560 x 1440) at Standard Size (100%)

**WTCS Gold v1.2**
![image](https://github.com/bluestillidie00/tcs5/assets/59927037/2a3caa73-44ac-4ad1-97f3-8b74beae4863)

**WTCS Gold v1.3**
![image](https://github.com/bluestillidie00/tcs5/assets/59927037/eed1b2c1-5faa-4f93-b899-49bfce98ea20)

**WTCS Gold v1.3.1**
![image](https://github.com/bluestillidie00/tcs5/assets/59927037/aa5fc0cc-b54b-4752-b7f5-7625ba21f0a7)

**Comment by bluestillidie00** [comment]
Fixed with 880cbcd
