### ISSUE TITLE
Inside a Match, The Tactics Screen Not Showing Possible Subs

### ISSUE THREAD

**Issue by biggitio** [bluestillidie00/tcs5#79]
In matches, when I click a player in the tactics window, the other players/subs don't show up beneath them to be chosen to swap out.
![Screenshot 2024-05-14 231034](https://github.com/bluestillidie00/tcs5/assets/169870732/0658eb4a-87c9-4697-af02-2e434201988e)
![Screenshot 2024-05-14 231002](https://github.com/bluestillidie00/tcs5/assets/169870732/49f9ea1a-27e6-4db8-a467-87d2e6af257d)

**Comment by bluestillidie00** [comment]
Fixed in v1.3.1
